theme: jekyll-theme-minimal
title: [Yimu Wang]
description: [Now I am a first year graduate student of Department of Computer Science and Technology in Nanjing University and a member of LAMDA Group, led by professor Zhi-Hua Zhou.]
google_analytics: [155379172]
logo: [pics.png]